
Turn 3
================================================================
error: failed to decode bot message: "T" (at position 1)
Last input received was:
Traceback (most recent call last):
  File "MyBot.py", line 184, in <module>
    if next_adj_positions[ship_id] == ship_paths[ship_id][0]:
IndexError: list index out of range

