
Turn 2
================================================================
error: failed to decode bot message: "T" (at position 1)
Last input received was:
Traceback (most recent call last):
  File "MyBot.py", line 77, in <module>
    set_long_target(ship)
  File "MyBot.py", line 28, in set_long_target
    if not has_arrival_coflict(ship, cell.position):
NameError: name 'has_arrival_coflict' is not defined

