
Turn 2
================================================================
error: failed to decode bot message: "T" (at position 1)
Last input received was:
Traceback (most recent call last):
  File "MyBot.py", line 127, in <module>
    move(ship)
  File "MyBot.py", line 94, in move
    ship_paths[ship_id].pop(0)
NameError: name 'ship_id' is not defined

