
Turn 2
================================================================
error: failed to decode bot message: "T" (at position 1)
Last input received was:
Traceback (most recent call last):
  File "RespawnBot.py", line 31, in <module>
    for position in ship.position.get_surounding_cardinals():
AttributeError: 'Position' object has no attribute 'get_surounding_cardinals'

