
Turn 2
================================================================
error: failed to decode bot message: "T" (at position 1)
Last input received was:
Traceback (most recent call last):
  File "MyBot.py", line 116, in <module>
    next_adj_positions[ship_id] = position
NameError: name 'position' is not defined

