
Turn 3
================================================================
error: failed to decode bot message: "T" (at position 1)
Last input received was:
Traceback (most recent call last):
  File "MyBot.py", line 82, in <module>
    if has_long_target(ship):
  File "MyBot.py", line 18, in has_long_target
    return true
NameError: name 'true' is not defined

